version: "3"

services:
  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test

  api:
    build:
      context: ./
    container_name: api
    restart: always
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: ./main

volumes:
  pgdata: